# Global Framework Configuration
browser=chrome
headless=false
implicit.wait=10
explicit.wait=20
page.load.timeout=30
retry.count=1
thread.count=3

# Report Paths
screenshot.path=screenshots/
extent.report.path=reports/extent-report.html
allure.results.path=target/allure-results
